version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    environment:
      - FLASK_RUN_HOST=0.0.0.0
